version: "3.9"

services:
  medbook-bookingservice:
    image: medbook-bookingservice
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    container_name: medbook-bookingservice
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: bitnami/postgresql:latest
    container_name: booking_service_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
